const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.bound,
		C3.Behaviors.custom,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event10_Act2,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event12_Act5,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event14_Act5,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.OnSignal
	];
};
self.C3_JsPropNameTable = [
	{TelaDeFundo: 0},
	{Sólido: 0},
	{Âncora: 0},
	{Chão1: 0},
	{Banco: 0},
	{Fonte: 0},
	{Portão: 0},
	{Banco2: 0},
	{Teclado: 0},
	{Mouse: 0},
	{RestritoAoLayout: 0},
	{Personalizado: 0},
	{Zumbi1: 0},
	{coração: 0},
	{cura1: 0},
	{vidas: 0},
	{cura: 0},
	{vida: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{chacal: 0},
	{caixa: 0},
	{Chão2: 0},
	{Chão3: 0},
	{Chão4: 0},
	{Senóide: 0},
	{seringa1: 0},
	{inicio: 0},
	{mundoz: 0},
	{iniciar: 0},
	{GamerOver: 0},
	{gameover: 0},
	{reiniciar: 0},
	{sair2: 0},
	{obrigado1: 0},
	{obrigado2: 0},
	{por: 0},
	{JOGAR: 0},
	{jogardenovo: 0},
	{sair3: 0},
	{zumbi2: 0},
	{Áudio: 0}
];

self.InstanceType = {
	TelaDeFundo: class extends self.ITiledBackgroundInstance {},
	Chão1: class extends self.ISpriteInstance {},
	Banco: class extends self.ISpriteInstance {},
	Fonte: class extends self.ISpriteInstance {},
	Portão: class extends self.ISpriteInstance {},
	Banco2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Zumbi1: class extends self.ISpriteInstance {},
	coração: class extends self.ISpriteInstance {},
	cura1: class extends self.ISpriteInstance {},
	vidas: class extends self.ITextInstance {},
	cura: class extends self.ITextInstance {},
	chacal: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Chão2: class extends self.ISpriteInstance {},
	Chão3: class extends self.ISpriteInstance {},
	Chão4: class extends self.ISpriteInstance {},
	seringa1: class extends self.ISpriteInstance {},
	inicio: class extends self.ISpriteInstance {},
	mundoz: class extends self.ITextInstance {},
	iniciar: class extends self.ITextInstance {},
	GamerOver: class extends self.ISpriteInstance {},
	gameover: class extends self.ITextInstance {},
	reiniciar: class extends self.ITextInstance {},
	sair2: class extends self.ITextInstance {},
	obrigado1: class extends self.ISpriteInstance {},
	obrigado2: class extends self.ITextInstance {},
	por: class extends self.ITextInstance {},
	JOGAR: class extends self.ITextInstance {},
	jogardenovo: class extends self.ITextInstance {},
	sair3: class extends self.ITextInstance {},
	zumbi2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}